[package]
name = "restork-storage"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
getrandom.workspace = true
rusqlite = { workspace = true, features = ["bundled"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
time = { workspace = true, features = ["formatting", "parsing"] }

[lib]
name = "restork_storage"
path = "src/lib.rs"
